image: Visual Studio 2017
configuration: Release

branches:
  only:
  - /-octiv$/

nuget:
  account_feed: false
  project_feed: true

before_build:
  - ps: nuget restore OpenXmlPowerTools.sln

build:
  project: OpenXmlPowerTools.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

cache:
  - packages -> **\packages.config   

